repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-added-large-files
  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
        name: "black (for data-ingest)"
        files: '^data-ingest/.*\.py'
  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
      - id: fmt
      - id: clippy
  - repo: http://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
