cargo-features = ["per-package-target"]

[package]
name = "heatmap-client"
version = "0.1.0"
edition = "2024"
forced-target = "wasm32-unknown-unknown"

[dependencies]
async-std = "1.12.0"
bytemuck = { version = "1.12", features = [ "derive" ] }
cgmath = { version = "0.18.0", features = ["swizzle"] }
console_error_panic_hook = "0.1.7"
console_log = "1.0.0"
earcutr = "0.4.3"
image = "0.25.1"
reqwest = { version = "0.12.5", features = ["json"] }
wasm-bindgen = "0.2.92"
wasm-bindgen-futures = "0.4.42"
web-sys = { version = "0.3.69", features = ["Document", "Window", "Element"] }
wgpu = { version = "0.20.1", features = ["webgl"] }
winit = { version = "0.30.3"}
js-sys = "0.3.69"
png = "0.17.13"
urlencoding = "2.1.3"
text-to-png = "0.2.0"
leptos = { version = "0.8.19", features = ["csr", "nightly"] }
serde = {version = "1.0.204", features = ["derive"] }
serde_json = "1.0.120"
chrono = "0.4.38"
log = "0.4.22"
geo = "0.28.0"
base64 = "0.22.1"
bincode = "2.0.1"
gloo-timers = { version = "=0.3.0", features = ["futures"] }
web-time = "1.1.0"
strum = { version = "0.28.0", features = ["strum_macros"] }
strum_macros = "0.28.0"

[build-dependencies]
reqwest = { version = " 0.12.5"}
tokio  = { version = "1.52.3", features = ["macros", "rt-multi-thread"]}

[lints.clippy]
unwrap_used = "warn"
