allowed-duplicate-crates = [
    "approx",
    "arrayvec",
    "async-channel",
    "base64",
    "bitflags",
    "convert_case",
    "core-foundation",
    "event-listener",
    "foldhash",
    "foreign-types",
    "foreign-types-shared",
    "getrandom",
    "hashbrown",
    "itertools",
    "jni-sys",
    "libloading",
    "linux-raw-sys",
    "memmap2",
    "ndk-sys",
    "png",
    "r-efi",
    "redox_syscall",
    "rustc-hash",
    "rustix",
    "syn",
    "thiserror",
    "thiserror-impl",
    "tiny-skia",
    "ttf-parser",
    "windows-core",
    "windows-sys",
]