[package]
name = "heatmap-api"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { workspace = true }
leptos = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true } 
bincode = { workspace = true }